# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gomoku.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from functools import partial
from gomuku import *


class Ui_Play_Game(object):
    def setupUi(self, Play_Game):
        Play_Game.setObjectName("Play_Game")
        Play_Game.setWindowModality(QtCore.Qt.NonModal)
        Play_Game.resize(499, 447)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(105, 165, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(75, 183, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 195, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 227, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 240, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        Play_Game.setPalette(palette)
        Play_Game.setFocusPolicy(QtCore.Qt.NoFocus)
        Play_Game.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Play_Game.setWindowIcon(icon)
        Play_Game.setWindowOpacity(1.0)
        Play_Game.setAutoFillBackground(False)
        Play_Game.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Play_Game)
        self.frame.setGeometry(QtCore.QRect(10, 10, 321, 321))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_4_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_9.setGeometry(QtCore.QRect(250, 100, 31, 31))
        self.pushButton_4_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_9.setText("")
        self.pushButton_4_9.setDefault(True)
        self.pushButton_4_9.setFlat(True)
        self.pushButton_4_9.setObjectName("pushButton_4_9")

        #self.pushButton_4_9.clicked.connect(partial(labeltext, "4_9", self.pushButton_4_9))

        self.pushButton_2_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_10.setGeometry(QtCore.QRect(280, 40, 31, 31))
        self.pushButton_2_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_10.setText("")
        self.pushButton_2_10.setDefault(True)
        self.pushButton_2_10.setFlat(True)
        self.pushButton_2_10.setObjectName("pushButton_2_10")

        #self.pushButton_2_10.clicked.connect(partial(labeltext, "2_10", self.pushButton_2_10))

        self.pushButton_9_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_2.setGeometry(QtCore.QRect(40, 250, 31, 31))
        self.pushButton_9_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_2.setText("")
        self.pushButton_9_2.setDefault(True)
        self.pushButton_9_2.setFlat(True)
        self.pushButton_9_2.setObjectName("pushButton_9_2")

        #self.pushButton_9_2.clicked.connect(partial(labeltext, "4_9", self.pushButton_4_9))

        self.pushButton_4_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_3.setGeometry(QtCore.QRect(70, 100, 31, 31))
        self.pushButton_4_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_3.setText("")
        self.pushButton_4_3.setDefault(True)
        self.pushButton_4_3.setFlat(True)
        self.pushButton_4_3.setObjectName("pushButton_4_3")

        #self.pushButton_4_3.clicked.connect(partial(labeltext, "4_3", self.pushButton_4_3))

        self.pushButton_8_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_2.setGeometry(QtCore.QRect(40, 220, 31, 31))
        self.pushButton_8_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_2.setText("")
        self.pushButton_8_2.setDefault(True)
        self.pushButton_8_2.setFlat(True)
        self.pushButton_8_2.setObjectName("pushButton_8_2")

        #self.pushButton_8_2.clicked.connect(partial(labeltext, "8_2", self.pushButton_8_2))

        self.pushButton_1_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_7.setGeometry(QtCore.QRect(190, 10, 31, 31))
        self.pushButton_1_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_7.setText("")
        self.pushButton_1_7.setDefault(True)
        self.pushButton_1_7.setFlat(True)
        self.pushButton_1_7.setObjectName("pushButton_1_7")

        #self.pushButton_1_7.clicked.connect(partial(labeltext, "1_7", self.pushButton_1_7))

        self.pushButton_5_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_3.setGeometry(QtCore.QRect(70, 130, 31, 31))
        self.pushButton_5_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_3.setText("")
        self.pushButton_5_3.setDefault(True)
        self.pushButton_5_3.setFlat(True)
        self.pushButton_5_3.setObjectName("pushButton_5_3")

       # self.pushButton_5_3.clicked.connect(partial(labeltext, "5_3", self.pushButton_5_3))

        self.pushButton_6_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_8.setGeometry(QtCore.QRect(220, 160, 31, 31))
        self.pushButton_6_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_8.setText("")
        self.pushButton_6_8.setDefault(True)
        self.pushButton_6_8.setFlat(True)
        self.pushButton_6_8.setObjectName("pushButton_6_8")

        #self.pushButton_4_9.clicked.connect(partial(labeltext, "4_9", self.pushButton_4_9))

        self.pushButton_10_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_10.setGeometry(QtCore.QRect(280, 280, 31, 31))
        self.pushButton_10_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_10.setText("")
        self.pushButton_10_10.setDefault(True)
        self.pushButton_10_10.setFlat(True)
        self.pushButton_10_10.setObjectName("pushButton_10_10")
        self.pushButton_3_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_8.setGeometry(QtCore.QRect(220, 70, 31, 31))
        self.pushButton_3_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_8.setText("")
        self.pushButton_3_8.setDefault(True)
        self.pushButton_3_8.setFlat(True)
        self.pushButton_3_8.setObjectName("pushButton_3_8")
        self.pushButton_2_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_5.setGeometry(QtCore.QRect(130, 40, 31, 31))
        self.pushButton_2_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_5.setText("")
        self.pushButton_2_5.setDefault(True)
        self.pushButton_2_5.setFlat(True)
        self.pushButton_2_5.setObjectName("pushButton_2_5")
        self.pushButton_2_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_2.setGeometry(QtCore.QRect(40, 40, 31, 31))
        self.pushButton_2_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_2.setText("")
        self.pushButton_2_2.setDefault(True)
        self.pushButton_2_2.setFlat(True)
        self.pushButton_2_2.setObjectName("pushButton_2_2")
        self.pushButton_10_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_7.setGeometry(QtCore.QRect(190, 280, 31, 31))
        self.pushButton_10_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_7.setText("")
        self.pushButton_10_7.setDefault(True)
        self.pushButton_10_7.setFlat(True)
        self.pushButton_10_7.setObjectName("pushButton_10_7")
        self.pushButton_10_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_9.setGeometry(QtCore.QRect(250, 280, 31, 31))
        self.pushButton_10_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_9.setText("")
        self.pushButton_10_9.setDefault(True)
        self.pushButton_10_9.setFlat(True)
        self.pushButton_10_9.setObjectName("pushButton_10_9")
        self.pushButton_4_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_8.setGeometry(QtCore.QRect(220, 100, 31, 31))
        self.pushButton_4_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_8.setText("")
        self.pushButton_4_8.setDefault(True)
        self.pushButton_4_8.setFlat(True)
        self.pushButton_4_8.setObjectName("pushButton_4_8")
        self.pushButton_10_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_5.setGeometry(QtCore.QRect(130, 280, 31, 31))
        self.pushButton_10_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_5.setText("")
        self.pushButton_10_5.setDefault(True)
        self.pushButton_10_5.setFlat(True)
        self.pushButton_10_5.setObjectName("pushButton_10_5")
        self.pushButton_2_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_7.setGeometry(QtCore.QRect(190, 40, 31, 31))
        self.pushButton_2_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_7.setText("")
        self.pushButton_2_7.setDefault(True)
        self.pushButton_2_7.setFlat(True)
        self.pushButton_2_7.setObjectName("pushButton_2_7")
        self.pushButton_7_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_1.setGeometry(QtCore.QRect(10, 190, 31, 31))
        self.pushButton_7_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_1.setText("")
        self.pushButton_7_1.setDefault(True)
        self.pushButton_7_1.setFlat(True)
        self.pushButton_7_1.setObjectName("pushButton_7_1")
        self.pushButton_8_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_9.setGeometry(QtCore.QRect(250, 220, 31, 31))
        self.pushButton_8_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_9.setText("")
        self.pushButton_8_9.setDefault(True)
        self.pushButton_8_9.setFlat(True)
        self.pushButton_8_9.setObjectName("pushButton_8_9")
        self.pushButton_6_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_7.setGeometry(QtCore.QRect(190, 160, 31, 31))
        self.pushButton_6_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_7.setText("")
        self.pushButton_6_7.setDefault(True)
        self.pushButton_6_7.setFlat(True)
        self.pushButton_6_7.setObjectName("pushButton_6_7")
        self.pushButton_5_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_6.setGeometry(QtCore.QRect(160, 130, 31, 31))
        self.pushButton_5_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_6.setText("")
        self.pushButton_5_6.setDefault(True)
        self.pushButton_5_6.setFlat(True)
        self.pushButton_5_6.setObjectName("pushButton_5_6")
        self.pushButton_8_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_10.setGeometry(QtCore.QRect(280, 220, 31, 31))
        self.pushButton_8_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_10.setText("")
        self.pushButton_8_10.setCheckable(False)
        self.pushButton_8_10.setDefault(True)
        self.pushButton_8_10.setFlat(True)
        self.pushButton_8_10.setObjectName("pushButton_8_10")
        self.pushButton_9_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_10.setGeometry(QtCore.QRect(280, 250, 31, 31))
        self.pushButton_9_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_10.setText("")
        self.pushButton_9_10.setDefault(True)
        self.pushButton_9_10.setFlat(True)
        self.pushButton_9_10.setObjectName("pushButton_9_10")
        self.pushButton_3_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_1.setGeometry(QtCore.QRect(10, 70, 31, 31))
        self.pushButton_3_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_1.setText("")
        self.pushButton_3_1.setDefault(True)
        self.pushButton_3_1.setFlat(True)
        self.pushButton_3_1.setObjectName("pushButton_3_1")
        self.pushButton_7_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_4.setGeometry(QtCore.QRect(100, 190, 31, 31))
        self.pushButton_7_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_4.setText("")
        self.pushButton_7_4.setDefault(True)
        self.pushButton_7_4.setFlat(True)
        self.pushButton_7_4.setObjectName("pushButton_7_4")
        self.pushButton_7_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_7.setGeometry(QtCore.QRect(190, 190, 31, 31))
        self.pushButton_7_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_7.setText("")
        self.pushButton_7_7.setDefault(True)
        self.pushButton_7_7.setFlat(True)
        self.pushButton_7_7.setObjectName("pushButton_7_7")
        self.pushButton_2_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_9.setGeometry(QtCore.QRect(250, 40, 31, 31))
        self.pushButton_2_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_9.setText("")
        self.pushButton_2_9.setDefault(True)
        self.pushButton_2_9.setFlat(True)
        self.pushButton_2_9.setObjectName("pushButton_2_9")
        self.pushButton_9_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_6.setGeometry(QtCore.QRect(160, 250, 31, 31))
        self.pushButton_9_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_6.setText("")
        self.pushButton_9_6.setDefault(True)
        self.pushButton_9_6.setFlat(True)
        self.pushButton_9_6.setObjectName("pushButton_9_6")
        self.pushButton_3_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_9.setGeometry(QtCore.QRect(250, 70, 31, 31))
        self.pushButton_3_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_9.setText("")
        self.pushButton_3_9.setDefault(True)
        self.pushButton_3_9.setFlat(True)
        self.pushButton_3_9.setObjectName("pushButton_3_9")
        self.pushButton_2_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_6.setGeometry(QtCore.QRect(160, 40, 31, 31))
        self.pushButton_2_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_6.setText("")
        self.pushButton_2_6.setAutoDefault(False)
        self.pushButton_2_6.setDefault(True)
        self.pushButton_2_6.setFlat(True)
        self.pushButton_2_6.setObjectName("pushButton_2_6")
        self.pushButton_10_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_1.setGeometry(QtCore.QRect(10, 280, 31, 31))
        self.pushButton_10_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_1.setText("")
        self.pushButton_10_1.setDefault(True)
        self.pushButton_10_1.setFlat(True)
        self.pushButton_10_1.setObjectName("pushButton_10_1")
        self.pushButton_1_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_2.setGeometry(QtCore.QRect(40, 10, 31, 31))
        self.pushButton_1_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_2.setText("")
        self.pushButton_1_2.setDefault(True)
        self.pushButton_1_2.setAutoDefault(True)
        self.pushButton_1_2.setFlat(True)
        self.pushButton_1_2.setObjectName("pushButton_1_2")
        self.pushButton_2_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_1.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.pushButton_2_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_1.setText("")
        self.pushButton_2_1.setDefault(True)
        self.pushButton_2_1.setFlat(True)
        self.pushButton_2_1.setObjectName("pushButton_2_1")
        self.pushButton_4_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_2.setGeometry(QtCore.QRect(40, 100, 31, 31))
        self.pushButton_4_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_2.setText("")
        self.pushButton_4_2.setDefault(True)
        self.pushButton_4_2.setFlat(True)
        self.pushButton_4_2.setObjectName("pushButton_4_2")
        self.pushButton_2_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_4.setGeometry(QtCore.QRect(100, 40, 31, 31))
        self.pushButton_2_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_4.setText("")
        self.pushButton_2_4.setDefault(True)
        self.pushButton_2_4.setFlat(True)
        self.pushButton_2_4.setObjectName("pushButton_2_4")
        self.pushButton_6_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_9.setGeometry(QtCore.QRect(250, 160, 31, 31))
        self.pushButton_6_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_9.setText("")
        self.pushButton_6_9.setDefault(True)
        self.pushButton_6_9.setFlat(True)
        self.pushButton_6_9.setObjectName("pushButton_6_9")
        self.pushButton_5_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_2.setGeometry(QtCore.QRect(40, 130, 31, 31))
        self.pushButton_5_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_2.setText("")
        self.pushButton_5_2.setDefault(True)
        self.pushButton_5_2.setFlat(True)
        self.pushButton_5_2.setObjectName("pushButton_5_2")
        self.pushButton_10_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_2.setGeometry(QtCore.QRect(40, 280, 31, 31))
        self.pushButton_10_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_2.setText("")
        self.pushButton_10_2.setDefault(True)
        self.pushButton_10_2.setFlat(True)
        self.pushButton_10_2.setObjectName("pushButton_10_2")
        self.pushButton_4_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_7.setGeometry(QtCore.QRect(190, 100, 31, 31))
        self.pushButton_4_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_7.setText("")
        self.pushButton_4_7.setDefault(True)
        self.pushButton_4_7.setFlat(True)
        self.pushButton_4_7.setObjectName("pushButton_4_7")
        self.pushButton_7_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_8.setGeometry(QtCore.QRect(220, 190, 31, 31))
        self.pushButton_7_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_8.setText("")
        self.pushButton_7_8.setDefault(True)
        self.pushButton_7_8.setFlat(True)
        self.pushButton_7_8.setObjectName("pushButton_7_8")
        self.pushButton_2_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_3.setGeometry(QtCore.QRect(70, 40, 31, 31))
        self.pushButton_2_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_3.setText("")
        self.pushButton_2_3.setDefault(True)
        self.pushButton_2_3.setFlat(True)
        self.pushButton_2_3.setObjectName("pushButton_2_3")
        self.pushButton_8_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_7.setGeometry(QtCore.QRect(190, 220, 31, 31))
        self.pushButton_8_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_7.setText("")
        self.pushButton_8_7.setDefault(True)
        self.pushButton_8_7.setFlat(True)
        self.pushButton_8_7.setObjectName("pushButton_8_7")
        self.pushButton_8_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_4.setGeometry(QtCore.QRect(100, 220, 31, 31))
        self.pushButton_8_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_4.setText("")
        self.pushButton_8_4.setDefault(True)
        self.pushButton_8_4.setFlat(True)
        self.pushButton_8_4.setObjectName("pushButton_8_4")
        self.pushButton_9_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_7.setGeometry(QtCore.QRect(190, 250, 31, 31))
        self.pushButton_9_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_7.setText("")
        self.pushButton_9_7.setDefault(True)
        self.pushButton_9_7.setFlat(True)
        self.pushButton_9_7.setObjectName("pushButton_9_7")
        self.pushButton_10_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_4.setGeometry(QtCore.QRect(100, 280, 31, 31))
        self.pushButton_10_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_4.setText("")
        self.pushButton_10_4.setDefault(True)
        self.pushButton_10_4.setFlat(True)
        self.pushButton_10_4.setObjectName("pushButton_10_4")
        self.pushButton_9_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_8.setGeometry(QtCore.QRect(220, 250, 31, 31))
        self.pushButton_9_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_8.setText("")
        self.pushButton_9_8.setDefault(True)
        self.pushButton_9_8.setFlat(True)
        self.pushButton_9_8.setObjectName("pushButton_9_8")
        self.pushButton_4_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_5.setGeometry(QtCore.QRect(130, 100, 31, 31))
        self.pushButton_4_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_5.setText("")
        self.pushButton_4_5.setDefault(True)
        self.pushButton_4_5.setFlat(True)
        self.pushButton_4_5.setObjectName("pushButton_4_5")
        self.pushButton_6_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_4.setGeometry(QtCore.QRect(100, 160, 31, 31))
        self.pushButton_6_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_4.setText("")
        self.pushButton_6_4.setDefault(True)
        self.pushButton_6_4.setFlat(True)
        self.pushButton_6_4.setObjectName("pushButton_6_4")
        self.pushButton_9_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_4.setGeometry(QtCore.QRect(100, 250, 31, 31))
        self.pushButton_9_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_4.setText("")
        self.pushButton_9_4.setDefault(True)
        self.pushButton_9_4.setFlat(True)
        self.pushButton_9_4.setObjectName("pushButton_9_4")
        self.pushButton_5_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_9.setGeometry(QtCore.QRect(250, 130, 31, 31))
        self.pushButton_5_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_9.setText("")
        self.pushButton_5_9.setDefault(True)
        self.pushButton_5_9.setFlat(True)
        self.pushButton_5_9.setObjectName("pushButton_5_9")
        self.pushButton_7_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_3.setGeometry(QtCore.QRect(70, 190, 31, 31))
        self.pushButton_7_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_3.setText("")
        self.pushButton_7_3.setDefault(True)
        self.pushButton_7_3.setFlat(True)
        self.pushButton_7_3.setObjectName("pushButton_7_3")
        self.pushButton_5_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_7.setGeometry(QtCore.QRect(190, 130, 31, 31))
        self.pushButton_5_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_7.setText("")
        self.pushButton_5_7.setDefault(True)
        self.pushButton_5_7.setFlat(True)
        self.pushButton_5_7.setObjectName("pushButton_5_7")
        self.pushButton_1_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_1.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton_1_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_1.setText("")
        self.pushButton_1_1.setAutoDefault(False)
        self.pushButton_1_1.setDefault(True)
        self.pushButton_1_1.setFlat(True)
        self.pushButton_1_1.setObjectName("pushButton_1_1")
        self.pushButton_1_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_10.setGeometry(QtCore.QRect(280, 10, 31, 31))
        self.pushButton_1_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_10.setText("")
        self.pushButton_1_10.setDefault(True)
        self.pushButton_1_10.setFlat(True)
        self.pushButton_1_10.setObjectName("pushButton_1_10")
        self.pushButton_5_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_1.setGeometry(QtCore.QRect(10, 130, 31, 31))
        self.pushButton_5_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_1.setText("")
        self.pushButton_5_1.setDefault(True)
        self.pushButton_5_1.setFlat(True)
        self.pushButton_5_1.setObjectName("pushButton_5_1")
        self.pushButton_7_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_6.setGeometry(QtCore.QRect(160, 190, 31, 31))
        self.pushButton_7_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_6.setText("")
        self.pushButton_7_6.setDefault(True)
        self.pushButton_7_6.setFlat(True)
        self.pushButton_7_6.setObjectName("pushButton_7_6")
        self.pushButton_8_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_6.setGeometry(QtCore.QRect(160, 220, 31, 31))
        self.pushButton_8_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_6.setText("")
        self.pushButton_8_6.setDefault(True)
        self.pushButton_8_6.setFlat(True)
        self.pushButton_8_6.setObjectName("pushButton_8_6")
        self.pushButton_1_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_9.setGeometry(QtCore.QRect(250, 10, 31, 31))
        self.pushButton_1_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_9.setText("")
        self.pushButton_1_9.setDefault(True)
        self.pushButton_1_9.setFlat(True)
        self.pushButton_1_9.setObjectName("pushButton_1_9")
        self.pushButton_3_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_4.setGeometry(QtCore.QRect(100, 70, 31, 31))
        self.pushButton_3_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_4.setText("")
        self.pushButton_3_4.setDefault(True)
        self.pushButton_3_4.setFlat(True)
        self.pushButton_3_4.setObjectName("pushButton_3_4")
        self.pushButton_3_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_10.setGeometry(QtCore.QRect(280, 70, 31, 31))
        self.pushButton_3_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_10.setText("")
        self.pushButton_3_10.setDefault(True)
        self.pushButton_3_10.setFlat(True)
        self.pushButton_3_10.setObjectName("pushButton_3_10")
        self.pushButton_4_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_6.setGeometry(QtCore.QRect(160, 100, 31, 31))
        self.pushButton_4_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_6.setText("")
        self.pushButton_4_6.setDefault(True)
        self.pushButton_4_6.setFlat(True)
        self.pushButton_4_6.setObjectName("pushButton_4_6")
        self.pushButton_6_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_10.setGeometry(QtCore.QRect(280, 160, 31, 31))
        self.pushButton_6_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_10.setText("")
        self.pushButton_6_10.setDefault(True)
        self.pushButton_6_10.setFlat(True)
        self.pushButton_6_10.setObjectName("pushButton_6_10")
        self.pushButton_2_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_8.setGeometry(QtCore.QRect(220, 40, 31, 31))
        self.pushButton_2_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_2_8.setText("")
        self.pushButton_2_8.setDefault(True)
        self.pushButton_2_8.setFlat(True)
        self.pushButton_2_8.setObjectName("pushButton_2_8")
        self.pushButton_3_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_5.setGeometry(QtCore.QRect(130, 70, 31, 31))
        self.pushButton_3_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_5.setText("")
        self.pushButton_3_5.setDefault(True)
        self.pushButton_3_5.setFlat(True)
        self.pushButton_3_5.setObjectName("pushButton_3_5")
        self.pushButton_6_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_6.setGeometry(QtCore.QRect(160, 160, 31, 31))
        self.pushButton_6_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_6.setText("")
        self.pushButton_6_6.setDefault(True)
        self.pushButton_6_6.setFlat(True)
        self.pushButton_6_6.setObjectName("pushButton_6_6")
        self.pushButton_7_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_5.setGeometry(QtCore.QRect(130, 190, 31, 31))
        self.pushButton_7_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_5.setText("")
        self.pushButton_7_5.setDefault(True)
        self.pushButton_7_5.setFlat(True)
        self.pushButton_7_5.setObjectName("pushButton_7_5")
        self.pushButton_6_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_3.setGeometry(QtCore.QRect(70, 160, 31, 31))
        self.pushButton_6_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_3.setText("")
        self.pushButton_6_3.setDefault(True)
        self.pushButton_6_3.setFlat(True)
        self.pushButton_6_3.setObjectName("pushButton_6_3")
        self.pushButton_8_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_1.setGeometry(QtCore.QRect(10, 220, 31, 31))
        self.pushButton_8_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_1.setText("")
        self.pushButton_8_1.setDefault(True)
        self.pushButton_8_1.setFlat(True)
        self.pushButton_8_1.setObjectName("pushButton_8_1")
        self.pushButton_6_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_1.setGeometry(QtCore.QRect(10, 160, 31, 31))
        self.pushButton_6_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_1.setText("")
        self.pushButton_6_1.setDefault(True)
        self.pushButton_6_1.setFlat(True)
        self.pushButton_6_1.setObjectName("pushButton_6_1")
        self.pushButton_7_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_2.setGeometry(QtCore.QRect(40, 190, 31, 31))
        self.pushButton_7_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_2.setText("")
        self.pushButton_7_2.setDefault(True)
        self.pushButton_7_2.setFlat(True)
        self.pushButton_7_2.setObjectName("pushButton_7_2")
        self.pushButton_5_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_4.setGeometry(QtCore.QRect(100, 130, 31, 31))
        self.pushButton_5_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_4.setText("")
        self.pushButton_5_4.setDefault(True)
        self.pushButton_5_4.setFlat(True)
        self.pushButton_5_4.setObjectName("pushButton_5_4")
        self.pushButton_10_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_8.setGeometry(QtCore.QRect(220, 280, 31, 31))
        self.pushButton_10_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_8.setText("")
        self.pushButton_10_8.setDefault(True)
        self.pushButton_10_8.setFlat(True)
        self.pushButton_10_8.setObjectName("pushButton_10_8")
        self.pushButton_5_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_10.setGeometry(QtCore.QRect(280, 130, 31, 31))
        self.pushButton_5_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_10.setText("")
        self.pushButton_5_10.setDefault(True)
        self.pushButton_5_10.setFlat(True)
        self.pushButton_5_10.setObjectName("pushButton_5_10")
        self.pushButton_10_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_6.setGeometry(QtCore.QRect(160, 280, 31, 31))
        self.pushButton_10_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_6.setText("")
        self.pushButton_10_6.setDefault(True)
        self.pushButton_10_6.setFlat(True)
        self.pushButton_10_6.setObjectName("pushButton_10_6")
        self.pushButton_7_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_10.setGeometry(QtCore.QRect(280, 190, 31, 31))
        self.pushButton_7_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_10.setText("")
        self.pushButton_7_10.setDefault(True)
        self.pushButton_7_10.setFlat(True)
        self.pushButton_7_10.setObjectName("pushButton_7_10")
        self.pushButton_8_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_3.setGeometry(QtCore.QRect(70, 220, 31, 31))
        self.pushButton_8_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_3.setText("")
        self.pushButton_8_3.setDefault(True)
        self.pushButton_8_3.setFlat(True)
        self.pushButton_8_3.setObjectName("pushButton_8_3")
        self.pushButton_9_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_1.setGeometry(QtCore.QRect(10, 250, 31, 31))
        self.pushButton_9_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_1.setText("")
        self.pushButton_9_1.setDefault(True)
        self.pushButton_9_1.setFlat(True)
        self.pushButton_9_1.setObjectName("pushButton_9_1")
        self.pushButton_1_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_3.setGeometry(QtCore.QRect(70, 10, 31, 31))
        self.pushButton_1_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_3.setText("")
        self.pushButton_1_3.setDefault(True)
        self.pushButton_1_3.setFlat(True)
        self.pushButton_1_3.setObjectName("pushButton_1_3")
        self.pushButton_5_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_5.setGeometry(QtCore.QRect(130, 130, 31, 31))
        self.pushButton_5_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_5.setText("")
        self.pushButton_5_5.setDefault(True)
        self.pushButton_5_5.setFlat(True)
        self.pushButton_5_5.setObjectName("pushButton_5_5")
        self.pushButton_3_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_2.setGeometry(QtCore.QRect(40, 70, 31, 31))
        self.pushButton_3_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_2.setText("")
        self.pushButton_3_2.setDefault(True)
        self.pushButton_3_2.setFlat(True)
        self.pushButton_3_2.setObjectName("pushButton_3_2")
        self.pushButton_5_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5_8.setGeometry(QtCore.QRect(220, 130, 31, 31))
        self.pushButton_5_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_5_8.setText("")
        self.pushButton_5_8.setDefault(True)
        self.pushButton_5_8.setFlat(True)
        self.pushButton_5_8.setObjectName("pushButton_5_8")
        self.pushButton_6_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_5.setGeometry(QtCore.QRect(130, 160, 31, 31))
        self.pushButton_6_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_5.setText("")
        self.pushButton_6_5.setDefault(True)
        self.pushButton_6_5.setFlat(True)
        self.pushButton_6_5.setObjectName("pushButton_6_5")
        self.pushButton_1_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_8.setGeometry(QtCore.QRect(220, 10, 31, 31))
        self.pushButton_1_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_8.setText("")
        self.pushButton_1_8.setDefault(True)
        self.pushButton_1_8.setFlat(True)
        self.pushButton_1_8.setObjectName("pushButton_1_8")
        self.pushButton_9_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_9.setGeometry(QtCore.QRect(250, 250, 31, 31))
        self.pushButton_9_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_9.setText("")
        self.pushButton_9_9.setDefault(True)
        self.pushButton_9_9.setFlat(True)
        self.pushButton_9_9.setObjectName("pushButton_9_9")
        self.pushButton_3_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_7.setGeometry(QtCore.QRect(190, 70, 31, 31))
        self.pushButton_3_7.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_7.setText("")
        self.pushButton_3_7.setDefault(True)
        self.pushButton_3_7.setFlat(True)
        self.pushButton_3_7.setObjectName("pushButton_3_7")
        self.pushButton_7_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7_9.setGeometry(QtCore.QRect(250, 190, 31, 31))
        self.pushButton_7_9.setStyleSheet("border: 1px solid black;")
        self.pushButton_7_9.setText("")
        self.pushButton_7_9.setDefault(True)
        self.pushButton_7_9.setFlat(True)
        self.pushButton_7_9.setObjectName("pushButton_7_9")
        self.pushButton_9_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_3.setGeometry(QtCore.QRect(70, 250, 31, 31))
        self.pushButton_9_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_3.setText("")
        self.pushButton_9_3.setDefault(True)
        self.pushButton_9_3.setFlat(True)
        self.pushButton_9_3.setObjectName("pushButton_9_3")
        self.pushButton_3_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_3.setGeometry(QtCore.QRect(70, 70, 31, 31))
        self.pushButton_3_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_3.setText("")
        self.pushButton_3_3.setDefault(True)
        self.pushButton_3_3.setFlat(True)
        self.pushButton_3_3.setObjectName("pushButton_3_3")
        self.pushButton_8_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_8.setGeometry(QtCore.QRect(220, 220, 31, 31))
        self.pushButton_8_8.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_8.setText("")
        self.pushButton_8_8.setDefault(True)
        self.pushButton_8_8.setFlat(True)
        self.pushButton_8_8.setObjectName("pushButton_8_8")
        self.pushButton_1_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_5.setGeometry(QtCore.QRect(130, 10, 31, 31))
        self.pushButton_1_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_5.setText("")
        self.pushButton_1_5.setDefault(True)
        self.pushButton_1_5.setFlat(True)
        self.pushButton_1_5.setObjectName("pushButton_1_5")
        self.pushButton_4_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_1.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.pushButton_4_1.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_1.setText("")
        self.pushButton_4_1.setDefault(True)
        self.pushButton_4_1.setFlat(True)
        self.pushButton_4_1.setObjectName("pushButton_4_1")
        self.pushButton_3_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3_6.setGeometry(QtCore.QRect(160, 70, 31, 31))
        self.pushButton_3_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_3_6.setText("")
        self.pushButton_3_6.setDefault(True)
        self.pushButton_3_6.setFlat(True)
        self.pushButton_3_6.setObjectName("pushButton_3_6")
        self.pushButton_10_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10_3.setGeometry(QtCore.QRect(70, 280, 31, 31))
        self.pushButton_10_3.setStyleSheet("border: 1px solid black;")
        self.pushButton_10_3.setText("")
        self.pushButton_10_3.setDefault(True)
        self.pushButton_10_3.setFlat(True)
        self.pushButton_10_3.setObjectName("pushButton_10_3")
        self.pushButton_6_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6_2.setGeometry(QtCore.QRect(40, 160, 31, 31))
        self.pushButton_6_2.setStyleSheet("border: 1px solid black;")
        self.pushButton_6_2.setText("")
        self.pushButton_6_2.setDefault(True)
        self.pushButton_6_2.setFlat(True)
        self.pushButton_6_2.setObjectName("pushButton_6_2")
        self.pushButton_4_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_4.setGeometry(QtCore.QRect(100, 100, 31, 31))
        self.pushButton_4_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_4.setText("")
        self.pushButton_4_4.setDefault(True)
        self.pushButton_4_4.setFlat(True)
        self.pushButton_4_4.setObjectName("pushButton_4_4")
        self.pushButton_1_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_4.setGeometry(QtCore.QRect(100, 10, 31, 31))
        self.pushButton_1_4.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_4.setText("")
        self.pushButton_1_4.setDefault(True)
        self.pushButton_1_4.setFlat(True)
        self.pushButton_1_4.setObjectName("pushButton_1_4")
        self.pushButton_1_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1_6.setGeometry(QtCore.QRect(160, 10, 31, 31))
        self.pushButton_1_6.setStyleSheet("border: 1px solid black;")
        self.pushButton_1_6.setText("")
        self.pushButton_1_6.setDefault(True)
        self.pushButton_1_6.setFlat(True)
        self.pushButton_1_6.setObjectName("pushButton_1_6")
        self.pushButton_8_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8_5.setGeometry(QtCore.QRect(130, 220, 31, 31))
        self.pushButton_8_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_8_5.setText("")
        self.pushButton_8_5.setDefault(True)
        self.pushButton_8_5.setFlat(True)
        self.pushButton_8_5.setObjectName("pushButton_8_5")
        self.pushButton_9_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9_5.setGeometry(QtCore.QRect(130, 250, 31, 31))
        self.pushButton_9_5.setStyleSheet("border: 1px solid black;")
        self.pushButton_9_5.setText("")
        self.pushButton_9_5.setDefault(True)
        self.pushButton_9_5.setFlat(True)
        self.pushButton_9_5.setObjectName("pushButton_9_5")
        self.pushButton_4_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4_10.setGeometry(QtCore.QRect(280, 100, 31, 31))
        self.pushButton_4_10.setStyleSheet("border: 1px solid black;")
        self.pushButton_4_10.setText("")
        self.pushButton_4_10.setDefault(True)
        self.pushButton_4_10.setFlat(True)
        self.pushButton_4_10.setObjectName("pushButton_4_10")

        self.pushButton_1_1.clicked.connect(partial(labeltext, "1_1", self.pushButton_1_1,self))
        self.pushButton_1_2.clicked.connect(partial(labeltext, "1_2", self.pushButton_1_2,self))
        self.pushButton_1_3.clicked.connect(partial(labeltext, "1_3", self.pushButton_1_3,self))
        self.pushButton_1_4.clicked.connect(partial(labeltext, "1_4", self.pushButton_1_4,self))
        self.pushButton_1_5.clicked.connect(partial(labeltext, "1_5", self.pushButton_1_5,self))
        self.pushButton_1_6.clicked.connect(partial(labeltext, "1_6", self.pushButton_1_6,self))
        self.pushButton_1_7.clicked.connect(partial(labeltext, "1_7", self.pushButton_1_7,self))
        self.pushButton_1_8.clicked.connect(partial(labeltext, "1_8", self.pushButton_1_8,self))
        self.pushButton_1_9.clicked.connect(partial(labeltext, "1_9", self.pushButton_1_9,self))
        self.pushButton_1_10.clicked.connect(partial(labeltext, "1_10", self.pushButton_1_10,self))

        self.pushButton_2_1.clicked.connect(partial(labeltext, "2_1", self.pushButton_2_1,self))
        self.pushButton_2_2.clicked.connect(partial(labeltext, "2_2", self.pushButton_2_2,self))
        self.pushButton_2_3.clicked.connect(partial(labeltext, "2_3", self.pushButton_2_3,self))
        self.pushButton_2_4.clicked.connect(partial(labeltext, "2_4", self.pushButton_2_4,self))
        self.pushButton_2_5.clicked.connect(partial(labeltext, "2_5", self.pushButton_2_5,self))
        self.pushButton_2_6.clicked.connect(partial(labeltext, "2_6", self.pushButton_2_6,self))
        self.pushButton_2_7.clicked.connect(partial(labeltext, "2_7", self.pushButton_2_7,self))
        self.pushButton_2_8.clicked.connect(partial(labeltext, "2_8", self.pushButton_2_8,self))
        self.pushButton_2_9.clicked.connect(partial(labeltext, "2_9", self.pushButton_2_9,self))
        self.pushButton_2_10.clicked.connect(partial(labeltext, "2_10", self.pushButton_2_10,self))

        self.pushButton_3_1.clicked.connect(partial(labeltext, "3_1", self.pushButton_3_1,self))
        self.pushButton_3_2.clicked.connect(partial(labeltext, "3_2", self.pushButton_3_2,self))
        self.pushButton_3_3.clicked.connect(partial(labeltext, "3_3", self.pushButton_3_3,self))
        self.pushButton_3_4.clicked.connect(partial(labeltext, "3_4", self.pushButton_3_4,self))
        self.pushButton_3_5.clicked.connect(partial(labeltext, "3_5", self.pushButton_3_5,self))
        self.pushButton_3_6.clicked.connect(partial(labeltext, "3_6", self.pushButton_3_6,self))
        self.pushButton_3_7.clicked.connect(partial(labeltext, "3_7", self.pushButton_3_7,self))
        self.pushButton_3_8.clicked.connect(partial(labeltext, "3_8", self.pushButton_3_8,self))
        self.pushButton_3_9.clicked.connect(partial(labeltext, "3_9", self.pushButton_3_9,self))
        self.pushButton_3_10.clicked.connect(partial(labeltext, "3_10", self.pushButton_3_10,self))

        self.pushButton_4_1.clicked.connect(partial(labeltext, "4_1", self.pushButton_4_1,self))
        self.pushButton_4_2.clicked.connect(partial(labeltext, "4_2", self.pushButton_4_2,self))
        self.pushButton_4_3.clicked.connect(partial(labeltext, "4_3", self.pushButton_4_3,self))
        self.pushButton_4_4.clicked.connect(partial(labeltext, "4_4", self.pushButton_4_4,self))
        self.pushButton_4_5.clicked.connect(partial(labeltext, "4_5", self.pushButton_4_5,self))
        self.pushButton_4_6.clicked.connect(partial(labeltext, "4_6", self.pushButton_4_6,self))
        self.pushButton_4_7.clicked.connect(partial(labeltext, "4_7", self.pushButton_4_7,self))
        self.pushButton_4_8.clicked.connect(partial(labeltext, "4_8", self.pushButton_4_8,self))
        self.pushButton_4_9.clicked.connect(partial(labeltext, "4_9", self.pushButton_4_9,self))
        self.pushButton_4_10.clicked.connect(partial(labeltext, "4_10", self.pushButton_4_10,self))

        self.pushButton_5_1.clicked.connect(partial(labeltext, "5_1", self.pushButton_5_1,self))
        self.pushButton_5_2.clicked.connect(partial(labeltext, "5_2", self.pushButton_5_2,self))
        self.pushButton_5_3.clicked.connect(partial(labeltext, "5_3", self.pushButton_5_3,self))
        self.pushButton_5_4.clicked.connect(partial(labeltext, "5_4", self.pushButton_5_4,self))
        self.pushButton_5_5.clicked.connect(partial(labeltext, "5_5", self.pushButton_5_5,self))
        self.pushButton_5_6.clicked.connect(partial(labeltext, "5_6", self.pushButton_5_6,self))
        self.pushButton_5_7.clicked.connect(partial(labeltext, "5_7", self.pushButton_5_7,self))
        self.pushButton_5_8.clicked.connect(partial(labeltext, "5_8", self.pushButton_5_8,self))
        self.pushButton_5_9.clicked.connect(partial(labeltext, "5_9", self.pushButton_5_9,self))
        self.pushButton_5_10.clicked.connect(partial(labeltext, "5_10", self.pushButton_5_10,self))

        self.pushButton_6_1.clicked.connect(partial(labeltext, "6_1", self.pushButton_6_1,self))
        self.pushButton_6_2.clicked.connect(partial(labeltext, "6_2", self.pushButton_6_2,self))
        self.pushButton_6_3.clicked.connect(partial(labeltext, "6_3", self.pushButton_6_3,self))
        self.pushButton_6_4.clicked.connect(partial(labeltext, "6_4", self.pushButton_6_4,self))
        self.pushButton_6_5.clicked.connect(partial(labeltext, "6_5", self.pushButton_6_5,self))
        self.pushButton_6_6.clicked.connect(partial(labeltext, "6_6", self.pushButton_6_6,self))
        self.pushButton_6_7.clicked.connect(partial(labeltext, "6_7", self.pushButton_6_7,self))
        self.pushButton_6_8.clicked.connect(partial(labeltext, "6_8", self.pushButton_6_8,self))
        self.pushButton_6_9.clicked.connect(partial(labeltext, "6_9", self.pushButton_6_9,self))
        self.pushButton_6_10.clicked.connect(partial(labeltext, "6_10", self.pushButton_6_10,self))

        self.pushButton_7_1.clicked.connect(partial(labeltext, "7_1", self.pushButton_7_1,self))
        self.pushButton_7_2.clicked.connect(partial(labeltext, "7_2", self.pushButton_7_2,self))
        self.pushButton_7_3.clicked.connect(partial(labeltext, "7_3", self.pushButton_7_3,self))
        self.pushButton_7_4.clicked.connect(partial(labeltext, "7_4", self.pushButton_7_4,self))
        self.pushButton_7_5.clicked.connect(partial(labeltext, "7_5", self.pushButton_7_5,self))
        self.pushButton_7_6.clicked.connect(partial(labeltext, "7_6", self.pushButton_7_6,self))
        self.pushButton_7_7.clicked.connect(partial(labeltext, "7_7", self.pushButton_7_7,self))
        self.pushButton_7_8.clicked.connect(partial(labeltext, "7_8", self.pushButton_7_8,self))
        self.pushButton_7_9.clicked.connect(partial(labeltext, "7_9", self.pushButton_7_9,self))
        self.pushButton_7_10.clicked.connect(partial(labeltext, "7_10", self.pushButton_7_10,self))

        self.pushButton_8_1.clicked.connect(partial(labeltext, "8_1", self.pushButton_8_1,self))
        self.pushButton_8_2.clicked.connect(partial(labeltext, "8_2", self.pushButton_8_2,self))
        self.pushButton_8_3.clicked.connect(partial(labeltext, "8_3", self.pushButton_8_3,self))
        self.pushButton_8_4.clicked.connect(partial(labeltext, "8_4", self.pushButton_8_4,self))
        self.pushButton_8_5.clicked.connect(partial(labeltext, "8_5", self.pushButton_8_5,self))
        self.pushButton_8_6.clicked.connect(partial(labeltext, "8_6", self.pushButton_8_6,self))
        self.pushButton_8_7.clicked.connect(partial(labeltext, "8_7", self.pushButton_8_7,self))
        self.pushButton_8_8.clicked.connect(partial(labeltext, "8_8", self.pushButton_8_8,self))
        self.pushButton_8_9.clicked.connect(partial(labeltext, "8_9", self.pushButton_8_9,self))
        self.pushButton_8_10.clicked.connect(partial(labeltext, "8_10", self.pushButton_8_10,self))

        self.pushButton_9_1.clicked.connect(partial(labeltext, "9_1", self.pushButton_9_1,self))
        self.pushButton_9_2.clicked.connect(partial(labeltext, "9_2", self.pushButton_9_2,self))
        self.pushButton_9_3.clicked.connect(partial(labeltext, "9_3", self.pushButton_9_3,self))
        self.pushButton_9_4.clicked.connect(partial(labeltext, "9_4", self.pushButton_9_4,self))
        self.pushButton_9_5.clicked.connect(partial(labeltext, "9_5", self.pushButton_9_5,self))
        self.pushButton_9_6.clicked.connect(partial(labeltext, "9_6", self.pushButton_9_6,self))
        self.pushButton_9_7.clicked.connect(partial(labeltext, "9_7", self.pushButton_9_7,self))
        self.pushButton_9_8.clicked.connect(partial(labeltext, "9_8", self.pushButton_9_8,self))
        self.pushButton_9_9.clicked.connect(partial(labeltext, "9_9", self.pushButton_9_9,self))
        self.pushButton_9_10.clicked.connect(partial(labeltext, "9_10", self.pushButton_9_10,self))

        self.pushButton_10_1.clicked.connect(partial(labeltext, "10_1", self.pushButton_10_1,self))
        self.pushButton_10_2.clicked.connect(partial(labeltext, "10_2", self.pushButton_10_2,self))
        self.pushButton_10_3.clicked.connect(partial(labeltext, "10_3", self.pushButton_10_3,self))
        self.pushButton_10_4.clicked.connect(partial(labeltext, "10_4", self.pushButton_10_4,self))
        self.pushButton_10_5.clicked.connect(partial(labeltext, "10_5", self.pushButton_10_5,self))
        self.pushButton_10_6.clicked.connect(partial(labeltext, "10_6", self.pushButton_10_6,self))
        self.pushButton_10_7.clicked.connect(partial(labeltext, "10_7", self.pushButton_10_7,self))
        self.pushButton_10_8.clicked.connect(partial(labeltext, "10_8", self.pushButton_10_8,self))
        self.pushButton_10_9.clicked.connect(partial(labeltext, "10_9", self.pushButton_10_9,self))
        self.pushButton_10_10.clicked.connect(partial(labeltext, "10_10", self.pushButton_10_10,self))
        #
        # self.New_Game = QtWidgets.QPushButton(Play_Game)
        # self.New_Game.setGeometry(QtCore.QRect(260, 400, 99, 27))
        # self.New_Game.setStyleSheet("")
        # self.New_Game.setDefault(True)
        # self.New_Game.setFlat(False)
        # self.New_Game.setObjectName("New_Game")
        self.Exit = QtWidgets.QDialogButtonBox(Play_Game)
        self.Exit.setGeometry(QtCore.QRect(380, 400, 99, 27))
        #self.Exit.setStyleSheet("")
        #self.Exit.setCheckable(False)
        #self.Exit.setAutoDefault(True)
        #self.Exit.setDefault(True)
        #self.Exit.setFlat(False)
        self.Exit.setObjectName("Exit")
        self.Exit.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.Exit.rejected.connect(Play_Game.reject)
        self.frame_2 = QtWidgets.QFrame(Play_Game)
        self.frame_2.setGeometry(QtCore.QRect(329, 9, 181, 321))
        self.frame_2.setStyleSheet("background-color: white;  ")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(16, 119, 151, 51))
        self.label.setText("")
        self.label.setObjectName("label")
        self.retranslateUi(Play_Game)
        QtCore.QMetaObject.connectSlotsByName(Play_Game)

    def retranslateUi(self, Play_Game):
        _translate = QtCore.QCoreApplication.translate
        Play_Game.setWindowTitle(_translate("Play_Game", "Play Game"))
        #self.New_Game.setText(_translate("Play_Game", "New Game"))
        #self.Exit.setText(_translate("Play_Game", "Exit"))



if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gomoku = QtWidgets.QDialog()
    window = Ui_Play_Game()
    window.setupUi(gomoku)
    gomoku.show()
    sys.exit(app.exec_())